[Server]
mode = "debug"
host = "127.0.0.1"
port = 3012

[DB]
types = "mysql"
host = "192.168.0.100:3306"
name = "go-service-api"
username = "go-service-api"
password = "wtYTYsdCLZRsy724"
charset = "utf8mb4"
